#!/bin/bash

DIRS=( $(find ~/git -mindepth 1 -maxdepth 3 -type f -name Vagrantfile -exec dirname {} \;) )
RUNNING=()
for d in "${DIRS[@]}"; do
  echo "Checking $d..."
  pushd $d 2&>1 /dev/null
  status=$(vagrant status | awk '/default/ {print $2}')
  if [ "${status}" == "running" ]; then
    RUNNING+=$d
  fi
  popd 2&>1 /dev/null
done

echo
echo
if [ "${#RUNNING[@]}" -gt 0 ]; then
  echo "The following directory(ies) contain(s) a running vagrant:"
  for d in "${RUNNING[@]}"; do
    echo "  $d"
  done
else
  echo "There are no running vagrants"
fi
